name: Deploy Registry Service
on:
  push:
    branches: [main]
    paths:
      - 'apps/registry-service/**'
      - 'packages/**'
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - name: Typecheck
        working-directory: apps/registry-service
        run: npm run typecheck
      - name: Deploy Registry Service
        working-directory: apps/registry-service
        run: npm run deploy:registry
